#!/bin/bash
# Fedora 28 Notes
me=`basename $0`
postinstall="PostInstallInstructions.md"
cat > $postinstall <<EOF
# Post Install Instructions
(This file was generated by $me, so
DO NOT EDIT THIS FILE)
EOF
#echo "(This file was generated by $me, so" > $postinstall
#echo "DO NOT EDIT THIS FILE)" >> $postinstall

# region for LAN computers only
# * faster owncloud if on same network:
# su -c 'echo "192.168.1.5 login.axlemedia.net" >> /etc/hosts'
# endregion for LAN computers only


# region local git website without database
# (see <https://www.git-scm.com/docs/git-instaweb/1.5.5>)
dnf -y install git-instaweb
# (which also gets: lighthttpd lighttpd-filesystem)
cat >> $postinstall <<EOF

## git-instaweb
(view local git repos using your web browser; not cloned repos--see
make-localhost-git-Bucket_Game.sh)
* cd to your git directory then run git instaweb such as
  \`\`\`bash
  cd /home/owner/localrepos/Bucket_Game.git
  git instaweb
  \`\`\`
EOF
# endregion local git website without database



# region even more unecessarily complicated stuff
# see "region local git website without database" instead
## for region nonworking, see instead:
## https://wiki.archlinux.org/index.php/gitweb
#dnf -y install httpd git gitweb
#if [ ! -f /etc/gitweb.conf.1st ]; then
    #if [ -f /etc/gitweb.conf ]; then
        #cp /etc/gitweb.conf /etc/gitweb.conf.1st
    #fi
#fi
#cat > /etc/gitweb.conf <<EOF
#our \$projectroot = "/home/owner/localrepos";
#EOF
#chown -R owner:www-data /home/owner/localrepos
#if [ ! -d /etc/httpd/conf.d/git.conf ]; then
#cat > /etc/httpd/conf.d/git.conf <<EOF
#DocumentRoot /var/www/git
#ServerName git.`hostname`

#Allow from all
#AllowOverride all
#Order allow,deny
#Options ExecCGI

#SetHandler cgi-script

#DirectoryIndex gitweb.cgi
#SetEnv  GITWEB_CONFIG  /etc/gitweb.conf
#EOF
#fi

#cat > /etc/httpd/conf.d/git.conf <<EOF
#Alias /gitweb "/usr/share/gitweb"
#<Directory "/usr/share/gitweb">
    #DirectoryIndex gitweb.cgi
    #Options ExecCGI
    #Require all granted
    #<Files gitweb.cgi>
    #SetHandler cgi-script
    #</Files>
    #SetEnv  GITWEB_CONFIG  /etc/gitweb.conf
#</Directory>
#EOF
#systemctl enable httpd
#systemctl restart httpd


## description is added by make-localhost-git-Bucket_Game.sh
## * then:
##   cd ~/localrepos/*
##   git-instaweb
## * make-localhost-no-network-repo-linux-minetest-kit.sh
# endregion even more unecessarily complicated stuff




# region nonworking
# see "region local git website without database" instead.
# dnf -y install docker docker-compose
# systemctl enable docker
# systemctl start docker

# see https://www.turnkeylinux.org/docs/docker
# dnf -y install mysql
#docker pull gitea/gitea
#docker run -i -t -d gitea/gitea
# if [ ! -d /root/gitea ]; then
#mkdir /root/gitea

#docker_gitea_USER_UID=`id -u g2345098itea`
#docker_gitea_USER_GID=`id -g g2345098itea`
#docker_gitea_DB_TYPE=postgres
#docker_gitea_DB_HOST=db:5432
#docker_gitea_DB_NAME=gi234598457tea
#docker_gitea_DB_USER=g2345098itea
#docker_gitea_DB_PASSWD=got3A123490872394087

# primarily based on <https://docs.gitea.io/en-us/install-with-docker/>,
# secondarily, <https://www.turnkeylinux.org/docs/docker>:
#cat > /root/gitea/inithooks.conf <<EOF
#export USER_UID=$docker_gitea_USER_UID
#export USER_GID=$docker_gitea_USER_GID
#export DB_TYPE=$docker_gitea_DB_TYPE
#export DB_HOST=$docker_gitea_DB_HOST
#export DB_NAME=$docker_gitea_DB_NAME
#export DB_USER=$docker_gitea_DB_USER
#export DB_PASSWD=$docker_gitea_DB_PASSWD
#export APP_EMAIL=owner@localhost
#export APP_DOMAIN=localhost
#export HUB_APIKEY=SKIP
#export SEC_UPDATES=FORCE
#EOF

## based on <https://www.turnkeylinux.org/docs/docker>:
##cat > /root/gitea/inithooks.conf <<EOF
##export ROOT_PASS=secretrootpass
##export DB_PASS=secretmysqlpass
##export APP_PASS=secretadminwppass
##export APP_EMAIL=admin@example.com
##export APP_DOMAIN=www.example.com
##export HUB_APIKEY=SKIP
##export SEC_UPDATES=FORCE
##EOF

##cat > /root/gitea/Dockerfile <<EOF
##FROM gitea/gitea
##ADD inithooks.conf /etc/inithooks.conf
##EOF
##docker build -t gitea /root/gitea
##cd /root
##docker run -i -t -d gitea
##yes | cp -f docker-compose.yml /root/
##cd /root
##docker-compose up -d
##echo "Listing services..."
##docker-compose ps

## The following should work, but some more steps are needed (not turnkey).
## See https://docs.gitea.io/en-us/install-with-docker/
##dnf -y install postgresql
##adduser g2345098itea
##echo got3A123490872394087 | passwd g2345098itea --stdin
##yes | cp -f docker-gitea.sql /tmp/
##chown postgres:postgres /tmp/docker-gitea.sql
##pushd /tmp
##sudo -u postgres psql --file=/tmp/docker-gitea.sql
##popd

# [regarding docker-compose.yml] "To bind the integrated openSSH daemon
# and the webserver on a different port, adjust the port section. It’s
# common to just change the host port and keep the ports within the
# container like they are" (docs.gitea.io).
# fi
#endregion nonworking


## auto-install
wget https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-28.noarch.rpm
wget https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-28.noarch.rpm
rpm -iv rpmfusion-free-release-28.noarch.rpm
dnf -y upgrade
rpm -iv rpmfusion-nonfree-release-28.noarch.rpm
dnf -y install blender inkscape gimp thunderbird chromium owncloud-client obs-studio keepassxc geany python python2-pillow python3-pillow speedcrunch filezilla darktable avidemux codeblocks qt-creator mypaint krita kate lmms vinagre scantailor vlc mpv librecad freecad gedit catfish meld hexchat ghex simple-scan audacity-freeworld gxmms2 python2-pygame gucharmap tiled evince fontforge qdirstat kdenlive frei0r-plugins redshift redshift-gtk plasma-applet-redshift-control projectM-pulseaudio eclipse-jdt java-1.8.0-openjdk-devel java-1.8.0-openjdk icedtea-web maven shotcut chromium-libs-media-freeworld exfat-utils fuse-exfat unetbootin gimp-elsamuko gimp-resynthesizer gimp-wavelet-denoise-plugin gimp-paint-studio gimp-lqr-plugin gimp-normalmap gimp-lensfun gimp-data-extras GREYCstoration-gimp star sloccount icoutils ladspa-cmt-plugins ladspa-autotalent-plugins ladspa-zam-plugins ladspa-rev-plugins PersonalCopy-Lite-soundfont ardour5 rhythmbox scribus discord libreoffice remarkable discord icoutils pandoc git gstreamer-ffmpeg sqlitebrowser

# for scale2x (see install-as-user.sh):
dnf -y install zlib libpng

# for testing php scripts such as via php -S localhost:8000 index.php:
dnf -y install php

# for butterflow (frame blending OR interpolation)--see install-as-user:
dnf -y install git python2-setuptools python2-virtualenv python2-numpy ocl-icd opencl-headers ffmpeg
# opencv-devel
# NOTE: as of Fedora 29, opencv-devel is opencv 3.4.1
# where ocl.hpp is totally DIFFERENT according to <https://stackoverflow.com/questions/34422276/opencv-3-0-error-include-ocl-hpp>
# not in readme, but if missing, prevents `pip install https://github.com/dthpham/butterflow/archive/master.zip`:
#    /tmp/pip-req-build-m6c87h1b/butterflow/avinfo.c:5:10: fatal error: libavcodec/avcodec.h: No such file or directory
#     #include <libavcodec/avcodec.h>
#              ^~~~~~~~~~~~~~~~~~~~~~
#    compilation terminated.
#    error: command 'gcc' failed with exit status 1
# could be solved by ffmpeg-compat-devel as per <https://ask.fedoraproject.org/en/question/31642/how-to-install-libav-devel-packages-properly/>
# but I installed ffmpeg-devel
# but error still occurs since ffmpeg has the h in ffmpeg/libavcodec/avcodec.h
# so edited butterflow/butterflow/avinfo.c to use that path
# still had error:
#    In file included from /tmp/pip-req-build-uquwiwd3/butterflow/avinfo.c:5:
#    /usr/include/ffmpeg/libavcodec/avcodec.h:31:10: fatal error: libavutil/samplefmt.h: No such file or directory
#     #include "libavutil/samplefmt.h"
#              ^~~~~~~~~~~~~~~~~~~~~~~
#    compilation terminated.
#    error: command 'gcc' failed with exit status 1
# so changed the two libavutil lines to use ffmpeg/libavutil as the path
# new error:
#    In file included from /tmp/pip-req-build-webiqhd6/butterflow/avinfo.c:5:
#    /usr/include/ffmpeg/libavcodec/avcodec.h:31:10: fatal error: libavutil/samplefmt.h: No such file or directory
#     #include "libavutil/samplefmt.h"
#              ^~~~~~~~~~~~~~~~~~~~~~~
#    compilation terminated.
#    error: command 'gcc' failed with exit status 1
#Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-webiqhd6/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-zettjosz/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-webiqhd6/
# * according to Eric Stdlib on <https://stackoverflow.com/questions/47562170/how-to-include-avcodec-h-in-c-in-fedora>
# the problem is solved by adding -I /usr/include/ffmpeg to the gcc command.
#   * I reverted back to the original butterflow/butterflow/avinfo.c (removed each ffmpeg/ added above)
#   * Path (-I) can be added via pip as per <https://stackoverflow.com/questions/18783390/python-pip-specify-a-library-directory-and-an-include-directory>
#     (see install-as-user)
# * another error remains:
#    /tmp/pip-req-build-gRg1yS/butterflow/ocl.cpp:10:10: fatal error: opencv2/ocl/ocl.hpp: No such file or directory
#     #include <opencv2/ocl/ocl.hpp>
#              ^~~~~~~~~~~~~~~~~~~~~
#    compilation terminated.
#    error: command 'gcc' failed with exit status 1
#
#    ----------------------------------------
#Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-gRg1yS/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-RA_EcH/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-gRg1yS/
#
#   * apparently since "opencv-ocl package or you did not compile your opencv with OCL activated." (see <https://github.com/slowmoVideo/slowmoVideo/issues/36>)
#     but there is no such package. locate says file is installed at: /usr/include/boost/compute/interop/opencv/ocl.hpp
#     so added interop to include path, but that doesn't work.
#   * Tried to install compat package from copr (see https://copr.fedorainfracloud.org/coprs/thofmann/opencv2/)
dnf -y install libav
#dnf -y copr enable thofmann/opencv2
# allowerasing will remove opencv (such as 3.0) if installed
# dnf -y --allowerasing install opencv2
# but install fails:
# Failed to synchronize cache for repo 'thofmann-opencv2', ignoring this repo.
# No match for argument: opencv2
# Error: Unable to find a match
#      * changing releasever to 26 doesn't work either (last build of thofmann-opencv2 <https://copr-be.cloud.fedoraproject.org/results/thofmann/opencv2/fedora-26-x86_64/repodata/>)
# No match for argument: opencv2
# Error: Unable to find a match
#   * tried installing python2-opencv, but as expected that did not help.
#   * so try including modules/ocl/include manually (see install-as-user)

# gstreamer-ffmpeg: should allow dragon player to play the files it opens by default but can't play by default (mkv, mp4, mov)
#source /etc/os-release
#if (( $VERSION_ID > 28 )) ; then
  # then use included gimp (29 has 2.10, 28 has 2.8 so use flatpak there)
#fi
#NOT lxmusic
#NOT bluez-hid2hci etc (see below for why using builtin KDE functionality instead)
#NOT retext (markdown editor for reStructuredText but not GitHub-style Markdown)
#use git version of git-cola since packaged version for Fedora 28 is git-cola 2.10, and May 2018 git version fixes consistency of Ctrl S
# (but explicitly install git above, since needed, and since otherwise removing git-cola will remove git)
# [closed: keyboard shortcuts doesn't work](https://github.com/git-cola/git-cola/issues/852)
#other keyboard shortcut issues:
#* [Ambiguous hotkeys by default for Alt+U (formerly triggered Stage Untracked) #926](https://github.com/git-cola/git-cola/issues/926)
dl_git="$HOME/Downloads/git"
if [ ! -d "$dl_git" ]; then
  mkdir -p "$dl_git"
fi
#cd "$dl_git"
#git clone git://github.com/git-cola/git-cola.git
#cd git-cola
#see unpriveleged.sh instead

#pandoc: convert from markdown to html (opposite by setting -f html -t markdown)
#remarkable: Markdown editor with GitHub markdown syntax support
#projectM-pulseaudio: The projectM visualization plugin for pulseaudio
#sloccount: Measures source lines of code (SLOC) in programs
#privacy-oriented browser:
sudo dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/
dnf -y install brave-keyring brave-browser

#for kivy:
dnf -y install python-devel ffmpeg-libs SDL2-devel SDL2_image-devel SDL2_mixer-devel SDL2_ttf-devel portmidi-devel libavdevice libavc1394-devel zlibrary-devel ccache mesa-libGL mesa-libGL-devel
dnf -y install python3-pip python2-pip xclip

#compatibility:
dnf -y msttcore-fonts wine-fonts wine-tahoma-fonts-system wine-times-new-roman-fonts-system wine-wingdings-fonts-system

dnf config-manager --add-repo https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo
dnf install sublime-text


#fix No valid kits found error in qtcreator
#(see <https://stackoverflow.com/questions/40978510/qt-creator-on-fedora-25-no-valid-kits-found>):
dnf -y install make gcc-c++ gdb qt5*-devel
#qt5-devel

#ignore xgalaga-sdl -- says works with SDL2 but configure fails on finding SDL (should compile with SDL1.2-devel packages though)
#SDL_gfxPrimitves (with alpha), SDL_rotozoom, SDL_framerate, SDL_imageFilter (with MMX), SDL_gfxBlitFunc (Custom Blit functions)
#such as for xgalaga-sdl `mkdir -p ~/Downloads/git && cd ~/Downloads/git && https://github.com/frank-zago/xgalaga-sdl.git`
#(successor to SDL_gfxPrimitives):
#dnf -y install SDL2_gfx-devel

#such as for XGalaga++ (C++ rewrite of XGalaga, but still pure X11):
dnf -y install libXpm-devel

#autoconf (including autoreconf etc):
dnf groupinstall "C Development Tools and Libraries"

#configure redshift (location for yourself can be found via Google Maps):
#where 5600 is day temp and 3400 is night temp
#redshift -l 40.3832256:-75.2748652 -t 5600:3400
#Has to remain running, so use GUI instead (drag widget to KDE panel, then right-click to configure:
# * turn on smooth transitions
# * set temps to 5600 and 3400
# * click Locate [if fails, use coords for your location such as above]
# * Apply

#projectM-pulseaudio: a GUI program for viewing audio input using MilkDrop scripts!
# * controlled using hotkeys (see F1 for help, and https://wiki.archlinux.org/index.php/ProjectM)
#

# BLUETOOTH:
# bluez-tools bluez-hid2hci blueman
# blueman pulls in: bluez-obexd (others didn't install anything additional)
# rfkill is not removeable. It was never manually installed (dnf history list rfkill says: "No transaction which manipulates package 'rfkill' was found.") and it can't be removed without removing systemd.
# Doing the above causes KDE to prompt for privs after login for both blueman and RfKill (separate prompt for each)
# Doing the above also results in two bluetooth symbol icons on the task tray (one blurry blue blueman one, plus one themed one)

source_fonts_path=/usr/share/wine/fonts
this_font_name=arial.ttf
this_font_path="$source_fonts_path/$this_font_name"
my_fonts_path=/usr/local/share/fonts/wine
if [ -f "$this_font_path" ]; then
  if [ ! -d "$my_fonts_path" ]; then
    sudo mkdir -p "$my_fonts_path"
  fi
  this_dest_path="$my_fonts_path/$this_font_name"
  if [ ! -f "$this_dest_path" ]; then
    if [ ! -L "$this_dest_path" ]; then
      echo "making symlink to $this_font_path..."
      sudo ln -s "$this_font_path" "$this_dest_path"
    else
      echo "NOTICE: redoing existing symlink $this_dest_path"
      sudo rm -f "$this_dest_path"
      sudo ln -s "$this_font_path" "$this_dest_path"
    fi
  else
    if [ ! -L "$this_dest_path" ]; then
      echo "WARNING: skipping font symlink $this_dest_path which is already a real file"
    else
      echo "NOTICE: redoing existing symlink $this_dest_path"
      sudo rm -f "$this_dest_path"
      sudo ln -s "$this_font_path" "$this_dest_path"
    fi
  fi
else
  echo "WARNING, font not present: $this_font_path"
fi

#also: wine-fonts wine-tahoma-fonts-system wine-times-new-roman-fonts-system wine-wingdings-fonts-system
#wine-*-system: wine font families system integration
#Calibri and Cambria compatible fonts (are installed by default?) respectively are:
sudo dnf -y install google-crosextra-carlito-fonts google-crosextra-caladea-fonts
#Make substitutions in libreoffice (see https://ask.libreoffice.org/en/question/15041/calibri-and-cambria-fonts-in-libreoffice/ which links to https://wiki.debian.org/SubstitutingCalibriAndCambriaFonts):

# * should already be in /etc/fonts/conf.d/
# * but will not work on new documents, only documents created on a computer with Calibri and Cambria
#Rename them (see https://superuser.com/questions/472102/change-font-family-rename-font):
sudo dnf -y install fontforge
# * open fontforge (gui)
if [ ! -d "$HOME/tmp/google-crosextra-carlito-as-calibri" ]; then

  mkdir -p "$HOME/tmp/google-crosextra-caladea-as-cambria"
  cp /usr/share/fonts/google-crosextra-caladea/* "$HOME/tmp/google-crosextra-caladea-as-cambria/"
  cd "$HOME/tmp/google-crosextra-caladea-as-cambria"
  mv Caladea-BoldItalic.ttf Cambria-BoldItalic.ttf
  mv Caladea-Bold.ttf Cambria-Bold.ttf
  mv Caladea-Italic.ttf Cambria-Italic.ttf
  mv Caladea-Regular.ttf Cambria-Regular.ttf

  mkdir -p "$HOME/tmp/google-crosextra-carlito-as-calibri"
  cp /usr/share/fonts/google-crosextra-carlito/* "$HOME/tmp/google-crosextra-carlito-as-calibri/"
  cd "$HOME/tmp/google-crosextra-carlito-as-calibri"
  mv Carlito-BoldItalic.ttf Calibri-BoldItalic.ttf
  mv Carlito-Bold.ttf Calibri-Bold.ttf
  mv Carlito-Italic.ttf Calibri-Italic.ttf
  mv Carlito-Regular.ttf Calibri-Regular.ttf

  # * fontforge "$HOME/tmp/google-crosextra-carlito-as-calibri/"
  # * fontforge "$HOME/tmp/google-crosextra-caladea-as-cambria"
  # * manually change names using fontforge or TTFEdit (java) or fpedit (Windows) from https://www.microsoft.com/typography/property/fpedit.htm
fi
  # * Element, Font Info...
#audacity-freeworld installs audacity with MP3 support
#evince: (aka "Document Viewer") pdf viewer better than okular

#optional
dnf -y install youtube-dl

cd
if [ ! -d "Downloads" ]; then
  mkdir Downloads
fi
wget http://download.brother.com/welcome/dlf006893/linux-brprinter-installer-2.2.0-1.gz
#or get latest from <http://support.brother.com/g/b/downloadhowto.aspx?c=us&lang=en&prod=mfcl2740dw_us_eu_as&os=127&dlid=dlf006893_000&flang=4&type3=625>
gunzip linux-brprinter-installer-2.2.0-1.gz
sudo bash linux-brprinter-installer-2.2.0-1 MFC-L2740DW

sudo dnf groupinstall "Development Tools"
echo "The correct package is `sudo dnf grouplist | grep Development | grep -v "D Development"`" >> $postinstall

#exit 0
echo "See 'Manually Install' section of this file for additional packages to install." >> $postinstall
## obsolete
# gnome-mplayer

## LXQt (an LXQt dev says 2019-03-31 that 0.13.0 included with Fedora 29 is "old")
#see https://github.com/lxqt/lxqt/wiki/Building-from-source
#for compiling lxqt (Qt deps):
dnf -y install qt5-qtbase-devel qt5-qtsvg-devel qt5-qttools-devel qt5-qtx11extras-devel
#for compiling lxqt (KDE deps):
dnf -y install kf5-kguiaddons-devel libkscreen-qt5-devel kf5-kidletime-devel kf5-kwindowsystem-devel kf5-solid-devel
#for compiling lxqt (misc deps):
dnf -y install systemd-devel bash libstatgrab-devel alsa-lib-devel pulseaudio-libs-devel lm_sensors-devel libconfig-devel muParser-devel upower-devel polkit-devel polkit-qt5-1-devel sudo libexif-devel xorg-x11-apps libSM-devel libXScrnSaver-devel libXcursor-devel libXcomposite-devel libxcb-devel xcb-util-devel libxkbcommon-x11-devel dbusmenu-qt5-devel libfm-devel menu-cache-devel lxmenu-data gtk-update-icon-cache hicolor-icon-theme xdg-utils xdg-user-dirs oxygen-icon-theme openbox openbox-devel
git submodule init
git submodule update --remote --rebase
xdg-mime default pcmanfm-qt.desktop inode/directory

cat >> $postinstall <<END
## screenshot hotkey for LXQt
By Default, LXQt (0.13.0 via @lxqt metapackage in Fedora 29)
- Runs the global hotkeys daemon (lxqt-globalkeysd) on startup
- Sets PrtScr ("Print" according to LXQt) key to run: lximage-qt -s
If it doesn't work, or you  require manual settings, see:
<https://www.pcsuggest.com/linux-screenshot-with-hotkeys/>
If it is already working and you just want to change the hotkey or
program, search the application menu for "Shortcut" and use the
"Shortcut Keys" program to change the setting.
END
dnf -y install lximage-qt scrot lxqt-globalkeys


cat >> $postinstall <<END
## Manually Install
* bluegriffon: graphical HTML editor [may mangle php]
* zerobrane-studio: Lua editor with the possibility of code completion
* gespeaker
* tsMuxeR
* COLMAP  # (2D to 3D) structure from motion
* GeekBench
* hardinfo  # System Profiler and Benchmark
* renpy [arch community]: Ren'Py is a visual novel engine that helps you use words, images, and sounds to tell interactive stories that run on computers and mobile devices


from source or flatpak for latest version:
  kdenlive
  openshot
  gimp  # if packaged version is not 2.10.8 yet
  #   (~2.10 has wavelet resize and denoise)
from source:
  minetest (see EnlivenMinetest)
  kivy (see above for dependencies)
  lxqt (see $me for packages already installed)

END

cat >> $postinstall <<END
### Change Settings via GUI:
For QT 5.* if you face error at Kits, like No Valid Kits Found, go to
Options->Build&Run-> then you see a Manual Option which included
Desktop as a default.

END

## see also (installed as dep)
# python3-mutagen (python module to handle audio meta-data)
if [ ! -d "$HOME/palettes" ]; then
    mkdir "$HOME/palettes"
fi
cat >> $postinstall <<END

see also Downloads/1.InstallManually
see also $HOME/ownCloud/Downloads
and try:
  cd ~/ownCloud/Downloads/Graphics,2D/gimp-stuff/
  chmod +x install-plugins
  ./install-plugins

To to via GUI"
* Install color profile from
  $HOME/ownCloud/Downloads/Drivers/Monitor/W2361VV-Windows7/
  or <https://www.lg.com/us/support-product/lg-W2361V-PF>
* Open your linux Desktop's System Settings,
  Color Corrections, Add Profile,
  then choose the downloaded icm profile.
* Enable plugins in Blender:
  - MeasureIT
  - Paint Palettes
    - You must manually set a full path to a palette directory such as:
      - Got to texture paint mode, tools side tab, Color Palette section
      - Paste $HOME/palettes/ (created by $me)
        or other (directory must exist and be writeable) into
        Palettes Folder box.
  - 3D Print Toolbox
  - Extra Objects
  - B3D Exporter (install from file--download github.com/minetest/ fork)
  -
END
if [ -f ../developer,any/install-voxelshop.sh ]; then
    bash ../developer,any/install-voxelshop.sh
elif [ -f install-voxelshop.sh ]; then
    bash install-voxelshop.sh
else
    echo "* The VoxelShop install script normally with this script was not found"
    echo "  (../developer,any/install-voxelshop.sh or install-voxelshop.sh)."
    echo "  You can install VoxelShop from https://github.com/simlu/voxelshop/releases"
fi
#dnf -y install psutils
#echo "psutils allows printing multiple pages per sheet:"
#echo "  psnup -4 file.ps print.ps"
#echo "  lpr print.ps"
#echo "according to https://www.cade.utah.edu/faqs/how-can-i-print-multiple-pages-per-sheet-in-linux/"
#echo "but tests were unsuccessful with `psnup -2 file.ps print.ps`."
dnf -y install pdfjam
#Debian-based: apt install pdfjam
#Arch-based: yaourt -S pdfnup
echo "pdfnup allows printing multiple pages per sheet (default is 2):"
echo "  pdfnup -o output.pdf input.pdf"


#unique folder so it doesn't erase other stuff you may be working on;
THIS_MAINTAINER=poikilos
if [ ! -d "$HOME/git" ]; then mkdir -p "$HOME/git"; fi
cd "$HOME/git"
#if [ -d "Gedit-External-Tools-SaveSession" ]; then rm -Rf "Gedit-External-Tools-SaveSession"; fi
git_url=https://github.com/$THIS_MAINTAINER/Gedit-External-Tools-SaveSession.git
if [ ! -d "Gedit-External-Tools-SaveSession" ]; then
  git clone $git_url
else
  cd Gedit-External-Tools-SaveSession
  git pull
  cd ..
fi
if [ ! -d "Gedit-External-Tools-SaveSession" ]; then
  echo "FAILED to get Gedit-External-Tools-SaveSession from $git_url" >> $postinstall
else
  cd "Gedit-External-Tools-SaveSession"
  bash install || echo "cd Gedit-External-Tools-SaveSession && bash install # FAILED" >> $postinstall
fi

adduser nonet
sudo iptables -A OUTPUT -m owner --uid-owner nonet -j REJECT
cat >> $postinstall <<END
nonet user has been denied internet on purpose.
If you want to allow the nonet user to have internet, undo as follows:
  sudo iptables -D OUTPUT -m owner --uid-owner nonet -j REJECT
Add the command without -D to /etc/rc.local if setting doesn't persist.

END
echo "Showing $postinstall..."
cat $postinstall
echo "(to see this generated post-install information again, see $postinstall)"
