version: "2"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=gi234598457tea
      - DB_USER=g2345098itea
      - DB_PASSWD=got3A123490872394087
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db
  db:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_USER=g2345098itea
      - POSTGRES_PASSWORD=got3A123490872394087
      - POSTGRES_DB=gi234598457tea
    networks:
      - gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data
