#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
import os

from find_pycodetool import pycodetool
# FIXME: move find_pycodetool to module & do: from linuxpreinstall.find_pycodetool import pycodetool
if __name__ == "__main__":
    SCRIPTS_DIR = os.path.dirname(os.path.realpath(__file__))
    sys.path.insert(0, os.path.dirname(SCRIPTS_DIR))

from pycodetool.changes import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
