#!/bin/bash
me=`basename $0`

# region common
postinstall="generated.md"
maindir=""
if [ -f api.rc ]; then
    maindir="."
elif [ -f ../api.rc ]; then
    maindir=".."
elif [ -f ../../api.rc ]; then
    maindir="../.."
elif [ -f ../../../api.rc ]; then
    maindir="../../.."
fi
if [ ! -z "$maindir" ]; then
    source $maindir/api.rc
    postinstall="$maindir/$_POSTINSTALL_NAME"
else
    echo "WARNING: api.rc cannot be found in `pwd` nor up to ../../.."
    echo "  tips will be placed in `pwd`/$postinstall instead."
fi
touch $postinstall
# endregion common

cat >> $postinstall <<EOF
# Post Install Instructions
(This file was generated by $me, so
DO NOT EDIT THIS FILE)
EOF


adduser nonet
sudo iptables -A OUTPUT -m owner --uid-owner nonet -j REJECT
cat >> $postinstall <<END
* nonet user has been denied internet on purpose.
  If you want to allow the nonet user to have internet, undo as follows:
    sudo iptables -D OUTPUT -m owner --uid-owner nonet -j REJECT
  Add the command without -D to /etc/rc.local if setting doesn't persist.

END
echo "Showing $postinstall..."
cat $postinstall
echo "(to see this generated post-install information again, see `pwd`/$postinstall)"
