#!/usr/bin/env python
"""
Find duplicate filenames.

For finding duplicate data, see
https://github.com/Poikilos/DupReaper
"""
from __future__ import print_function
import os
import sys

from find_linuxpreinstall import linuxpreinstall

from linuxpreinstall import (
    echo0,
)

from linuxpreinstall.dupset import DupSet

def main():
    if len(sys.argv) < 2:
        echo0("Error: no path(s) were specified.")
        return 1
    paths = []
    paths.append(sys.argv[1])
    if len(sys.argv) > 2:
        paths.append(sys.argv[2])
    if len(sys.argv) > 3:
        raise ValueError("Expected only 1 or 2 paths.")
    dupset = DupSet()
    for path in paths:
        dupset.check(path)
    dupset.print_summary()
    return 0


if __name__ == "__main__":
    sys.exit(main())