#!/bin/bash
# See <https://www.fosslinux.com/46761/recursively-find-list-the-files-by-dat-linux.htm>
# find "`pwd`" -type f -printf '%T@ %t %p\n' | sort -k 1 -n | cut -d ' ' -f2-
# ^ type f: only files
# ^ type d: only directories
find "`pwd`" -iname "*$1*"
