#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
import os
import platform

profile = os.environ.get('HOME')
if platform.system() == "Windows":
    profile = os.environ['USERPROFILE']

tryRepo = os.path.join(profile, "git", "linux-preinstall")
tryModule = os.path.join(tryRepo, "linuxpreinstall")

thisRepo = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

if os.path.isdir(os.path.join(thisRepo, "linuxpreinstall")):
    sys.path.insert(0, thisRepo)
    print("[ggrep] using own {}".format(thisRepo))
elif os.path.isdir(tryModule):
    sys.path.insert(0, tryRepo)
    print("[ggrep] using git {}".format(tryRepo))
else:
    pass
    # use the one in the python path (or fail)
    # print("There is no {}".format(os.path.join(thisRepo, "linuxpreinstall")))

try:
    from linuxpreinstall.ggrep import main
except ImportError as ex:
    print("ggrep is a Python module now. You must install the repo:")
    print("# Clone it then:")
    print("python3 -m pip install linux-preinstall")


if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
