#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
import os
import platform

from find_hierosoft import hierosoft

from hierosoft.ggrep import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
