#!/bin/bash

# This is a quiet meld launcher.

if [ ! -f "`command -v nohup`" ]; then
    echo "$0 requires nohup"
    exit 1
fi
if [ ! -f "`command -v meld`" ]; then
    echo "$0 requires meld"
    exit 1
fi

if [ -f "$1" ]; then
    if [ ! -f "$2" ]; then
        echo "Cannot compare a file ('$1') to something that is not a file ('$2')"
        exit 1
    fi
fi

if [ ! -z "$3" ]; then
    if [ -f "$1" ]; then
        if [ ! -f "$3" ]; then
            echo "Cannot compare a file ('$1') to something that is not a file ('$3')"
            exit 1
        fi
    fi
    nohup meld "$1" "$2" "$3" >& /dev/null &
else
    nohup meld "$1" "$2" >& /dev/null &
fi


#Doesn't work, so check for files first:
#if [ $? -ne 0 ]; then
#    echo "ERROR, showing..."
#    nohup meld "$1" "$2" "$3"
#fi
