#!/bin/sh
# cd "$(dirname "$0")";
# CWD="$(pwd)"
# echo $CWD
OUTFILE=/var/log/linuxpreinstall.rsnapshot_logged.sh.out
TMPFILE=/var/log/linuxpreinstall.rsnapshot_logged.sh.tmp
LOG=/var/log/linuxpreinstall.rsnapshot_logged.sh.log

python3 /opt/bin/rsnapshot_logged.py "$1" 1>$OUTFILE 2>$LOG
RESULT_RC=/opt/etc/rsnapshot-generated.rc

if [ -f "$RESULT_RC" ]; then
    # ^ generated by rsnapshot_logged.py
    . $RESULT_RC
    if [ -z "$snapshot_root" ]; then
        echo "Error: no snapshot_root in $RESULT_RC" >> $LOG
    else
        if [ -z "$backup_drive" ]; then
            echo "Error: no snapshot_root in $RESULT_RC" >> $LOG
        else
             echo "cp $LOG $backup_drive/var/log/"
             cp $LOG "$backup_drive/var/log/" 1>>$OUTFILE 2>>$TMPFILE
             # ^ TMPFILE since can't read & write same file in same pipeline!
             if [ -f "$TMPFILE" ]; then
                 cat $TMPFILE >> $LOG
                 rm $TMPFILE
             fi
             echo "cp $OUTFILE $backup_drive/var/log/"
             cp $OUTFILE "$backup_drive/var/log/" 1>>$TMPFILE 2>>$LOG
             # ^ TMPFILE since can't read & write same file in same pipeline!
             if [ -f "$TMPFILE" ]; then
                 cat $TMPFILE >> $OUTFILE
                 rm $TMPFILE
             fi
        fi
    fi
else
    echo "Error: missing $RESULT_RC" >> $LOG
fi