#!/bin/sh
# cd "$(dirname "$0")";
# CWD="$(pwd)"
# echo $CWD

# TODO: Copy then delete mail messages: cron uses the "mail" command to record any stderr output produced.
# See also `grep rsnapshot /var/log/syslog`

OUTFILE=/var/log/linuxpreinstall.rsnapshot_logged.sh.out
TMPFILE=/var/log/linuxpreinstall.rsnapshot_logged.sh.tmp
LOG=/var/log/linuxpreinstall.rsnapshot_logged.sh.log

python3 /opt/bin/rsnapshot_logged.py "$1" 1>$OUTFILE 2>$LOG
RESULT_RC=/opt/etc/rsnapshot-generated.rc

if [ ! -f "$RESULT_RC" ]; then
    # ^ generated by rsnapshot_logged.py
    echo "Error: missing $RESULT_RC" >> $LOG
fi
. $RESULT_RC
if [ -z "$snapshot_root" ]; then
    echo "Error: no snapshot_root in $RESULT_RC" >> $LOG
    return 2
fi

if [ -z "$backup_drive" ]; then
    echo "Error: no backup_drive in $RESULT_RC" >> $LOG
    return 3
fi

if [ -z "$dst_logs" ]; then
    echo "Error: no dst_logs in $RESULT_RC" >> $LOG
    return 3
fi

if [ ! -d "$dst_logs" ]; then
    echo "Error: rsnapshot_logged.py did not create the dst_logs folder \"$dst_logs\"." >> $LOG
    return 3
fi

echo "cp $LOG $dst_logs/"
cp $LOG "$dst_logs/" 1>>$OUTFILE 2>>$TMPFILE
# ^ TMPFILE since can't read & write same file in same pipeline!
if [ -f "$TMPFILE" ]; then
    cat $TMPFILE >> $LOG
    rm $TMPFILE
fi
echo "cp $OUTFILE $dst_logs/"
cp $OUTFILE "$dst_logs/" 1>>$TMPFILE 2>>$LOG
# ^ TMPFILE since can't read & write same file in same pipeline!
if [ -f "$TMPFILE" ]; then
    cat $TMPFILE >> $OUTFILE
    rm $TMPFILE
fi
