#!/usr/bin/env python3
from __future__ import print_function
import re
import sys

from find_linuxpreinstall import linuxpreinstall

from linuxpreinstall.versioning import main


if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
