#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
import platform
import os
profile = None
if platform.system() == "Windows":
    profile = os.environ['USERPROFILE']
else:
    profile = os.environ['HOME']
reposDir = os.path.join(profile, "git")
tryRepos = []
MODULE_DIR = os.path.dirname(os.path.realpath(__file__))
REPO_DIR = os.path.dirname(MODULE_DIR)
tryRepos.append(REPO_DIR)
tryRepos.append(os.path.join(reposDir, "linux-preinstall"))

for tryRepo in tryRepos:
    if os.path.isfile(os.path.join(tryRepo, "linuxpreinstall", "__init__.py")):
        sys.path.insert(0, tryRepo)
        break

from linuxpreinstall.thingi import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
