#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import re
import sys


SCRIPTS_DIR = os.path.dirname(os.path.realpath(__file__))
REPO_DIR = os.path.dirname(SCRIPTS_DIR)
if os.path.isfile(os.path.join(REPO_DIR, "linuxpreinstall", "whichicon.py")):
    sys.path.insert(0, REPO_DIR)

from linuxpreinstall.whichicon import main


if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
