#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
import os
import platform

profile = os.environ.get('HOME')
if platform.system() == "Windows":
    profile = os.environ['USERPROFILE']

tryRepo = os.path.join(profile, "git", "linux-preinstall")
tryModule = os.path.join(tryRepo, "linuxpreinstall")

MY_MODULE = os.path.dirname(os.path.abspath(__file__))
MY_REPO = os.path.dirname(MY_MODULE)
MY_REPOS = os.path.dirname(MY_REPO)

nearbyRepo = os.path.join(MY_REPOS, "linux-preinstall")
# repos = [nearbyRepo, tryRepo]

def echo0(*args, **kwargs):  # formerly prerr
    print(*args, file=sys.stderr, **kwargs)

if os.path.isfile(os.path.join(nearbyRepo, "linuxpreinstall", "zcimages.py")):
    sys.path.insert(0, nearbyRepo)
    echo0("[zc-make-sized-images] using nearby {}".format(nearbyRepo))
elif os.path.isdir(tryModule):
    sys.path.insert(0, tryRepo)
    echo0("[zc-make-sized-images] using git {}".format(tryRepo))
else:
    pass
    # use the one in the python path (or fail)
    # print("There is no {}".format(os.path.join(thisRepo, "linuxpreinstall")))

try:
    from linuxpreinstall.server.zcimages import main
except ImportError as ex:
    echo0(str(ex))
    '''
    echo0("zcimages is a Python module in linuxpreinstall now. You must install the repo:")
    echo0("# Clone it then:")
    echo0("python3 -m pip install linux-preinstall")
    echo0('# or just put it in a directory near here such as via:')
    echo0('  git clone https://github.com/poikilos/linux-preinstall'
          ' "{}"'.format(nearbyRepo))
    '''
    echo0('The command couldn\'t be found in either nearby directory "{}"'
          ' (also tried a common path: "{}")'
          ''.format(nearbyRepo, tryRepo))
    sys.exit(1)


if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
