#!/bin/sh
### BEGIN INIT INFO
# Provides:          ulauncher
# Required-Start:    $network $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: A fancy python3-based launcher with a UI toggled via the ulauncher-toggle shell script.
### END INIT INFO


# IGNORE THIS FILE:
# THIS SERVICE UNIT DOESN'T WORK EVEN IF "owner" BELOW IS CHANGED TO THE CORRECT USER.


# This file is by Poikilos and available in the
# everyone/jwm/etc/init.d directory on https://github.com/Hierosoft/linux-preinstall
# - It is based on the service file /etc/init.d/nohang from the nohang package in the Devuan 4 (Chimaera) repository.
# - dbus looks for a service named but the Debian service script says:
#   "start-stop-daemon: warning: this system is not able to track process names
#   longer than 15 characters, please use --exec instead of --name."

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC=ulauncher
NAME=ulauncher
DAEMON=/home/owner/.local/bin/ulauncher
PIDFILE=/run/$NAME.pid
LOGFILE=/var/log/$NAME.log
USER="owner"

# Exit if the package is not installed
#[ -x $DAEMON ] || exit 0

[ -r /etc/default/$NAME ] && . /etc/default/$NAME
. /lib/init/vars.sh
. /lib/lsb/init-functions

# Function that starts the daemon/service
do_start()
{
  # Return
  #   0 if daemon has been started
  #   1 if daemon was already running
  #   2 if daemon could not be started

  touch "$PIDFILE"

  start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --chuid "$USER" --test > /dev/null \
    || return 1
  start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --chuid "$USER" -- \
    $DAEMON_OPTS > /dev/null 2>&1 \
    || return 2
  return $?
}

# Function that stops the daemon/service
do_stop()
{
  # Return
  #   0 if daemon has been stopped
  #   1 if daemon was already stopped
  #   2 if daemon could not be stopped
  #   other if a failure occurred
  start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
  RETVAL="$?"
  [ "$RETVAL" = 2 ] && return 2
  start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
  [ "$?" = 2 ] && return 2
  rm -f $PIDFILE
  return "$RETVAL"
}

case "$1" in
  start)
    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC " "$NAME"
    do_start
    case "$?" in
      0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
      2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
    esac
    ;;
  stop)
    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
    do_stop
    case "$?" in
      0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
      2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
    esac
    ;;
  status)
    status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
    ;;
  reload|force-reload|restart)
    log_daemon_msg "Restarting $DESC" "$NAME"
    do_stop
    case "$?" in
      0|1)
      do_start
      case "$?" in
        0) log_end_msg 0 ;;
        1) log_end_msg 1 ;; # Old process is still running
        *) log_end_msg 1 ;; # Failed to start
      esac
      ;;
      *)
        # Failed to stop
      log_end_msg 1
      ;;
    esac
    ;;
  *)
    echo "Usage: $0 {start|stop|status|restart|reload}" >&2
    exit 3
    ;;
esac

:
