#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import re
import sys
import os

SCRIPTS_DIR = os.path.dirname(os.path.realpath(__file__))
MODULES_DIR = os.path.dirname(SCRIPTS_DIR)

if os.path.isfile(os.path.join(MODULES_DIR, "linuxpreinstall", "__init__.py")):
    sys.path.insert(0, MODULES_DIR)

from linuxpreinstall.phpversion import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
